"""Generate C semantic constants exclusively from the Python reference.

The move catalog is static public data from the exact pinned simulator.
Run after an intentional schema change; preflight checks regeneration.
"""
import json
import subprocess
from pathlib import Path
from gen3rl.features.encoder import classify_role
from gen3rl.features.move_semantics import classify_move, _TYPE_CHART
from gen3rl.features.schema import TYPE_NAMES, GEN3_PHYSICAL_TYPES

ROOT=Path(__file__).resolve().parents[1]

def render():
    moves=json.loads(subprocess.check_output(["node",str(ROOT/"scripts/export_move_catalog.cjs")],text=True))
    rows=[[0,0,0] for _ in range(355)]; metadata=[[17,0,-1,0] for _ in range(355)]
    for m in moves:
        mid=m["id"]; flags=0
        if mid in {"struggle","futuresight","doomdesire"}: flags|=1
        if mid in {"dreameater","nightmare"}: flags|=2
        if m.get("target") not in {"self","allySide","allyTeam","all"}:
            if mid in {"thunderwave","glare"}: flags|=4
            if m.get("status") in {"psn","tox"}: flags|=8
            if m.get("status")=="brn": flags|=16
            if mid=="leechseed": flags|=32
            if m.get("status"): flags|=64
        rows[m["num"]]=[int(classify_move(m)),int(classify_role(m)),flags]
        acc=m.get("accuracy",True)
        metadata[m["num"]]=[TYPE_NAMES.index(m["type"].lower()) if m["type"].lower() in TYPE_NAMES else 17,
            m["basePower"],-1 if acc is True else acc,m["priority"]]
    chart=[[9 if _TYPE_CHART[a].get(d,0) is None else _TYPE_CHART[a].get(d,0) for d in TYPE_NAMES[:17]] for a in TYPE_NAMES[:17]]
    def array(name,values):
        return f"static const int16_t {name}[{len(values)}][{len(values[0])}] = {{\n"+",\n".join("{"+",".join(map(str,r))+"}" for r in values)+"\n};\n"
    return ("/* Generated by scripts/generate_c_reference.py; gen3-lut-v1.1. */\n#include <stdint.h>\n"
        +array("rl_chart",chart)+array("rl_moves",rows)+array("rl_move_metadata",metadata)
        +"static const uint8_t rl_physical[18] = {"+",".join(str(int(t in GEN3_PHYSICAL_TYPES or t=="unknown")) for t in TYPE_NAMES)+"};\n")

if __name__=="__main__":
    (ROOT/"integration/reference/semantics.generated.h").write_text(render())
